### PR TITLE
Try the private IP if the public IP is not available when ssh'ing

### PR DESCRIPTION
**Pull request by thecarlhall**

### CODE REVIEW

**Comment by achiku** [comment]
@thecarlhall Sorry for being late to reply, but thank you for the pr! Could you add some tests for where you modified?

**Comment by thecarlhall** [comment]
Hi, @achiku.  I'm just back from holiday and will try to add those tests very soon.

**Comment by thecarlhall** [comment]
@achiku I finally got around to adding some tests for the new code.  I consolidated a couple of places where I used this into a function, too.

**Comment by achiku** [comment]
@thecarlhall Thanks!

**Pull request merged**
