### PR TITLE
Added profile parameter

### PR DESCRIPTION
**Pull request by padilo**
Added parameter to use jungle with profiles defined on your ~/.aws/credentials

### CODE REVIEW

**Comment by padilo** [comment]
No sure but I think the missing tests on emr is the problem, can you take a look? :)

**Comment by achiku** [comment]
@padilo Thanks! Could you explain why we need this? I think you can simply change env vars for different AWS credentials.

**Comment by padilo** [comment]
I have two aws profiles based in environments (staging, production), that
are nearly identic so I prefer an explicit way to know which one I'm
hitting when doing ssh, usign environtment variables is very prompt to
error in this case.

Of course, if you are just using one account you would be more confortable
with environment variables. With this PR usign environment variables will
work too.

**Comment by edubxb** [comment]
I have the same use case that @padilo explains. Allowing profiles is more versatile than changing env vars when using several accounts.

**Comment by achiku** [comment]
Thanks! Merged!

**Pull request merged**
